### ISSUE TITLE
Class: information about relationships/associations

### ISSUE THREAD

**Issue by FChikh** [BESSER-PEARL/BESSER-UML#7]
Standard UML and/or ODL models associate relations between Classes directly to them; should the instance of Class type has information about all relationships it is involved in?

**Comment by ivan-alfonso** [comment]
Feature added (#13).

Now, it is possible to obtain the list of associations and generalizations in which a class is involved, using the following methods:

`class_obj.associations()`
`class_obj.generalizations()`
